version: "3.5"

services:
  namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
  datanode:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
  hive-server:
    build: .
    container_name: hive-server
    env_file:
      - ./hadoop-hive.env
    environment:
      - "HADOOP_CLASSPATH=/opt/hadoop-3.1.1/share/hadoop/tools/lib/*:/opt/hive/hcatalog/share/hcatalog/*"
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    ports:
      - "10000:10000"
  hive-metastore:
    build: .
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
  hive-metastore-postgresql:
    image: mhessconnectify/hive-metastore-postgresql:latest

networks:
  default:
    name: hivenet
    driver: bridge
